apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: mern
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client  # Change based on your cloud provider
  resources:
    requests:
      storage: 2Gi