apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mern
type: Opaque
data:
  root-password: cGFzc3dvcmQxMjM= # base64 encoded "password123"
  root-username: YXBwdXNlcg== # "appuser"
  username: YXBwdXNlcg== # "appuser"
  password: YXBwcGFzc3dvcmQxMjM= # "apppassword123"